### ISSUE TITLE
TODO sample, text input, loses focus after each key press

### ISSUE THREAD

**Issue by Robinyo** [Wildhoney/Switzerland#15]
## Issue Summary
When trying to enter a TODO item, the text input loses focus after each key press:

![screenshot from 2017-08-20 10 43 18](https://user-images.githubusercontent.com/12203540/29491110-810bf7be-8594-11e7-9160-dd8a9addd155.png)

### Technical details:
- https://switzerland.herokuapp.com/
- Client OS: Elementary OS 0.3.2 (64-bit)
- Chromium Version 59.0.3071.109 (Developer Build) Built on Ubuntu

**Comment by Wildhoney** [comment]
Thanks @Robinyo &mdash; [should be all fixed now](https://switzerland.herokuapp.com/). Possibly caused by an update in Webkit.
