### ISSUE TITLE
https://jsfiddle.net/chs2fnod/ console errors in Chromium and Firefox

### ISSUE THREAD

**Issue by Robinyo** [Wildhoney/Switzerland#16]
## Issue Summary

JSFiddle error in console: Cannot find file "/dist/switzerland.browser.js" in package switzerland@0.6.1

![screenshot from 2017-08-20 10 50 16](https://user-images.githubusercontent.com/12203540/29491133-6a58610a-8595-11e7-8e78-3d1e38bb37dc.png)

### Technical details:
- https://jsfiddle.net/chs2fnod/
- Client OS: Elementary OS 0.3.2 (64-bit)
- Chromium Version 59.0.3071.109 (Developer Build) Built on Ubuntu

JSFiddle errors in console:

![screenshot from 2017-08-20 10 55 58](https://user-images.githubusercontent.com/12203540/29491163-2eb93ae2-8596-11e7-8377-42495577207b.png)

### Technical details:
- https://jsfiddle.net/chs2fnod/
- Client OS: Elementary OS 0.3.2 (64-bit)
- Firefox 54.0 (64-bit)

**Comment by Wildhoney** [comment]
Sorry, it's because I accidentally added the JS include twice. [Should be fixed here](https://jsfiddle.net/ynbLsda4/).
