### ISSUE TITLE
Integrate hyperHTML

### ISSUE THREAD

**Issue by Wildhoney** [Wildhoney/Switzerland#20]
https://github.com/WebReflection/hyperHTML

**Comment by drejohnson** [comment]
What about [lit-html](https://github.com/Polymer/lit-html) integration also?

**Comment by tylerkrett** [comment]
suck a lemon mate a big lemon we don't need lit-lemon

**Comment by luwes** [comment]
I love the concept of this library! 

Was wondering how this new view library hyperHTML would be integrated?
Is it a tight integration or would it be possible to have multiple view rendering options?

**Comment by Wildhoney** [comment]
The idea is that we'd have multiple view rendering options.

Would you like to take a look at adding it to `v3.0.0`?

**Comment by luwes** [comment]
Sorry, really need IE 11 support. I was thinking of branching this off in a likewise project but limited to only the `custom element` aspect of web components which is easily polyfilled in older browsers.
