### ISSUE TITLE
Browser support (IE11)

### ISSUE THREAD

**Issue by luwes** [Wildhoney/Switzerland#24]
Are there any plans to support most used browsers of today?
So far the library is using quite new web technologies.

I made an attempt to add IE11 support for the todo app but didn't get there yet.
https://github.com/luwes/Switzerland/commit/82ae781799cffe93a5d5273e83233c7870d593e8

**Comment by Wildhoney** [comment]
Nope it's not a goal of this project. It's far too problematic in supporting older browsers. There's a [polyfill](https://github.com/Wildhoney/Switzerland/blob/master/example/app/index.html#L10) that goes some way to adding support, but it still has a whole host of problems, such as styles bleeding across shadow boundaries.
