### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Lodin** [Wildhoney/Switzerland#9]
Is there any plans for adding typescript typings? It is very promising project and I think it would be great if it is able to be used in typescript-written projects.

**Comment by Wildhoney** [comment]
@Lodin Thanks. I have no plans to add the typings &ndash; however if you would like to contribute, I'd be more than happy to add TypeScript 👍

**Comment by jmjpro** [comment]
@Wildhoney suggest to add a `Help Wanted` tag

**Comment by tylerkrett** [comment]
why would you want this.....

**Comment by Wildhoney** [comment]
New version is in TypeScript :) thanks @jmjpro
